version: 4.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\rqlite\rqlite

environment:
  GOPATH: c:\gopath
  CIVERS: rqlited-4.%APPVEYOR_BUILD_VERSION%-ci-%APPVEYOR_BUILD_ID%-win64

install:
  - set BUILD_ENV=gnu
  - if %BUILD_ENV%==gnu  set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
  - if %BUILD_ENV%==gnu  set MSYSTEM=MINGW64
  - if %BUILD_ENV%==gnu  set MSYS=winsymlinks=lnk

build_script:
  - go get ./...
  - go build -i ./...
  - go test -v ./...

after_build:
  - 7z a %CIVERS%.zip %GOPATH%\bin\rq*.exe

artifacts:
  - path: %CIVERS%.zip
    name: rqlite 4.{build} for Windows (64bit)
