os: Visual Studio 2019

stack: go 1.16

version: 6.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\rqlite\rqlite

environment:
  GOPATH: c:\gopath

install:
  - set BUILD_ENV=gnu
  - if %BUILD_ENV%==gnu  set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
  - if %BUILD_ENV%==gnu  set MSYSTEM=MINGW64
  - if %BUILD_ENV%==gnu  set MSYS=winsymlinks=lnk

build_script:
  - go version
  - go get ./...
  - go build -i ./...
  - go test ./...

after_build:
  - 7z a rqlite-latest-win64.zip %GOPATH%\bin\rq*.exe

artifacts:
  - path: rqlite-latest-win64.zip
    name: rqlite for Windows x64
